### PR TITLE
Add note to set PKG_CONFIG_PATH when required

### PR DESCRIPTION
**Pull request by m-schmoock**

### CODE REVIEW

**Comment by evoskuil** [comment]
This is standard autotools behavior, which we don’t document.

**Comment by m-schmoock** [comment]
Okay. Why does my Autotools behave otherwise ?

**Comment by evoskuil** [comment]
It’s not a question of non-standard behavior, just of what to document. There are a multitude of autotools options and configurations which can be customized to affect the builds. This setting is not necessary under default configuration. So if people have a different environment they may have to configure the build accordingly in various ways.

**Comment by m-schmoock** [comment]
Hi @evoskuil , I researched a bit.

As far as I know, your `README.md` build instruction will fail with linkage errors on every standard linux system, as `pkg-config` will not search in `/usr/local`, see:

- https://askubuntu.com/questions/210210/pkg-config-path-environment-variable/210235#210235
- https://people.freedesktop.org/~dbn/pkg-config-guide.html
- https://unix.stackexchange.com/questions/8241/how-to-make-pkg-config-path-variable-to-refer-an-installed-library/8246#8246

We should even change this PR to generally point that out like this:
```sh
$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
$ sudo ldconfig
```

If you still think otherwise, feel free to close this and the other related PRs.

**Comment by evoskuil** [comment]
Yet it does not fail at least on Debian. I have never set this path.

**Comment by m-schmoock** [comment]
Your right on Debian it states https://manpages.debian.org/stretch/pkg-config/pkg-config.1.en.html that `/usr/local/lib/pkgconfig` is included, however this seems a specialty of Debian according to my short research. At least not on widely used Arch, Ubuntu and some Unix derivatives.

**Comment by evoskuil** [comment]
Ubuntu is Debian. We don’t test on (ie support) Unix variants.

**Comment by m-schmoock** [comment]
Regardless, Ubuntu does not look in `/usr/local/lib/pkgconfig` as users report: https://askubuntu.com/questions/210210/pkg-config-path-environment-variable/210235#210235

Arch user also specifically report this issue related to libbitcoin: https://bitcoin.stackexchange.com/a/73955

**Comment by m-schmoock** [comment]
Alternatively, you could point out that the build instructions will only work on generic Debian.

**Pull request closed without merging**
